### PR TITLE
Variable to define Jira home directory

### PR DESCRIPTION
**Pull request by mttjohnson**
I would like to be able to override the Jira home directory during an install, so I have added a variable so that it is defined as a default in the role instead of hard coded in multiple places, and this allows me to override the default variable when I include the role.

```
    - role: alvistack.jira
      jira_home_dir: /data/atlassian/application-data/jira
```

### CODE REVIEW

**Comment by hswong3i** [comment]
Not such easy, something else should be done.

BTW, within my working schedule, please wait for a while ;-)

**Comment by mttjohnson** [comment]
I am currently using the fork I created `classyllama/ansible-role-jira` where I replaced various hard coded paths with a variable in template files, and have the variable overridden when the role is called. The defaults on the role are `/var/atlassian/application-data/jira` but I can easily change this to `/data/atlassian/application-data/jira` by specifying variable definitions when calling the role.

```
    - role: alvistack.jira
      jira_home_dir: /data/atlassian/application-data/jira
```

**Comment by hswong3i** [comment]
@mttjohnson please give a hand and comment for https://github.com/alvistack/ansible-role-bamboo/commit/b8ef48ea9abcf4b99587296f419d90f711176886

If this looks good I will also apply similar changes for Jira.

**Comment by hswong3i** [comment]
Please also check this https://github.com/alvistack/ansible-role-jira/commit/541a2cbe0957b50131a777f1012af9244900b4a4

Beside just works, I will also consider code lint and also the use in docker image https://github.com/alvistack/docker-jira/blob/a309888beeaee9369ed617fdb08bf21fde00ab9f/files/etc/ansible/roles/localhost/molecule/default/playbook.yml

**Comment by hswong3i** [comment]
Done by https://github.com/alvistack/ansible-role-jira/commit/541a2cbe0957b50131a777f1012af9244900b4a4

**Comment by mttjohnson** [comment]
Yes, adding support for the catalina install directory in addition to the home directory as a variable is great, that should work well.

It looks like you also applied these changes on the confluence role which I'm also using and needing the same thing for, thank you.

Thank you for adding support for this!

**Pull request closed without merging**
